version: '2.1'

services:
   backend:
     container_name: $CONTAINER_NAME
     image: $IMAGE_RUNTIME
     ports:
       - '80:8000'
     environment:
       VENV_DIR: /$VENV_DIR
     volumes:
       - './$APP_DIR:/$APP_DIR'
       - './$VENV_DIR:/$VENV_DIR'
       - './wait-for-it.sh:/wait-for-it.sh'
     depends_on:
      - mysql
     entrypoint: /wait-for-it.sh -t 10 mysql:3306 -- /resources/runservices.sh

   mysql:
     container_name: mysql
     image: mariadb
     volumes:
       - ./mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: $MYSQL_PWD
       MYSQL_DATABASE: $MYSQL_DB_NAME
     ports:
       - $MYSQL_PORT:3306

   adminer:
     container_name: adminer
     image: adminer
     ports:
      - 8080:8080
     depends_on:
      - mysql

networks:
  default:
    external:
      name: $DOCKER_NETWORK